// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	h "mercado/app/helpers/home"
	expense "mercado/app/models/expense"
	stringsUtils "mercado/utils/strings"
	"strconv"
)

var showGroceryStoreSelectorHeader = false

func ExpensesListItem(expense expense.Expense) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script type=\"text/javascript\">\n        function formatCurrency(inputValue) {\n            const numericValue = inputValue.replace(/\\D/g, \"\");\n            const decimalValue = Number(numericValue) / 100;\n            return decimalValue.toFixed(2);\n        }\n\n        function handleEdit(e) {\n            this.editing = true;\n\n            const parentLi = e.target.closest(\"li\");\n            const input = parentLi.querySelector(\"input\");\n\n            setTimeout(() => {\n                input.value = formatCurrency(input.value);\n                input.focus();\n                input.setSelectionRange(0, input.value.length);\n            }, 0);\n        }\n\n        function handleDelete(e) {\n            const parentLi = e.target.closest(\"li\");\n            const dialog = parentLi.querySelector(\"dialog\");\n\n            dialog.showModal();\n        }\n\n        function handleCancelDelete(e) {\n            const parentLi = e.target.closest(\"li\");\n            const dialog = parentLi.querySelector(\"dialog\");\n            dialog.close();\n        }\n    </script><li class=\"expense-list-item p-4 mb-4 rounded shadow-md\" x-data=\"{ editing: false }\"><dialog class=\"rounded\"><div class=\"p-8\"><h3>Certzinha que quer deletar isso?</h3><div class=\"flex items-center space-x-6 mt-3\"><button @click=\"handleCancelDelete\" class=\"text-blue-500 p-2\">Melhor não</button> <button class=\"text-red-500 p-2\" hx-delete=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(strconv.Itoa(expense.ID)))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-target=\"closest .expense-list-item\" hx-swap=\"outerHTML\">Sim, Deletar</button></div></div></dialog><div x-show=\"!editing\" class=\"flex\"><div class=\"flex-1\"><div class=\"flex items-center space-x-2\"><span class=\"text-lg font-semibold\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(stringsUtils.FormatCurrency(expense.Value))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/home/expenses_list_item.templ`, Line: 70, Col: 85}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span><div class=\"text-gray-600\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(expense.GroceryStore)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/home/expenses_list_item.templ`, Line: 71, Col: 54}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><span class=\"text-xs\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(h.FormatDate(expense.Date))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/home/expenses_list_item.templ`, Line: 73, Col: 54}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span></div><div class=\"flex space-x-4 items-center\"><button @click=\"handleEdit\" class=\"ml-auto text-blue-500\">Editar</button> <button @click=\"handleDelete\" class=\"text-red-500 flex items-center space-x-1\"><svg class=\"w-4 h-4\" viewBox=\"0 0 24 24\" width=\"auto\" height=\"100%\" xmlns=\"http://www.w3.org/2000/svg\" fill-rule=\"evenodd\" clip-rule=\"evenodd\" fill=\"currentColor\"><path d=\"M19 24h-14c-1.104 0-2-.896-2-2v-17h-1v-2h6v-1.5c0-.827.673-1.5 1.5-1.5h5c.825 0 1.5.671 1.5 1.5v1.5h6v2h-1v17c0 1.104-.896 2-2 2zm0-19h-14v16.5c0 .276.224.5.5.5h13c.276 0 .5-.224.5-.5v-16.5zm-9 4c0-.552-.448-1-1-1s-1 .448-1 1v9c0 .552.448 1 1 1s1-.448 1-1v-9zm6 0c0-.552-.448-1-1-1s-1 .448-1 1v9c0 .552.448 1 1 1s1-.448 1-1v-9zm-2-7h-4v1h4v-1z\"></path></svg></button></div></div><div x-show=\"editing\" class=\"mt-2\"><form hx-post=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString("/edit/" + strconv.Itoa(expense.ID)))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-target=\"closest .expense-list-item\" hx-swap=\"outerHTML\"><span><label htmlFor=\"value\" class=\"block text-sm font-medium mb-1\">Valor</label><div x-data=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(`{expenseValue : "` + strconv.Itoa(expense.Value) + `" }`))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><input name=\"value\" @input=\"handleInputChange\" x-model=\"expenseValue\" type=\"text\" inputmode=\"decimal\" class=\"w-full border border-gray-300 px-2 py-1 rounded\"><div class=\"mt-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = GroceryStoreSelector(expense.GroceryStore, showGroceryStoreSelectorHeader).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></span> <button type=\"submit\" class=\"w-full mt-2 px-4 py-2 bg-blue-500 text-white rounded\">Salvar</button></form></div></li>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
